sitl:
  startup_delay: 10

mission:
  takeoff_altitude: 10
  hover_time: 10

paths:
  px4_log_dir: ~/PX4-Autopilot/build/px4_sitl_default/logs
  
  thresholds:
  altitude_rmse: 1.5
  velocity_rmse: 1.0
  attitude_rmse: 5.0
